version: '2'
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        volumes:
            - ./mysql-data/db:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD : cryptobets
            MYSQL_DATABASE      : cryptobets
            MYSQL_USER          : cryptobets
            MYSQL_PASSWORD      : cryptobets
        command:
            - "mysqld"
            - "--character-set-server=utf8"
            - "--lower_case_table_names=1"
            - "--character_set_client=utf8"
        networks:
            - crytpobets-network
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - 2181:2181
        networks:
            - crytpobets-network
    kafka:
        image: wurstmeister/kafka
        ports:
            - 9092:9092
        environment:
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_MESSAGE_MAX_BYTES: 2000000
            KAFKA_CREATE_TOPICS: "receptionTopic:1:1,winnerTopic:1:1"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - zookeeper
        networks:
            - crytpobets-network
    config-service:
        container_name: config-service
        build:
            context: config
            dockerfile: Dockerfile
        image: config-service:latest
        ports:
            - 8888:8888
        networks:
            - crytpobets-network
    discovery-service:
        container_name: discovery-service
        build:
            context: discovery
            dockerfile: Dockerfile
        image: discovery-service:latest
        ports:
            - 8761:8761
        networks:
            - crytpobets-network
    gateway-service:
        container_name: gateway-service
        build:
            context: gateway
            dockerfile: Dockerfile
        image: gateway-service:latest
        ports:
            - 8080:8080
        networks:
            - crytpobets-network
    cryptobets-service:
        container_name: cryptobets-service
        build:
            context: cryptobets
            dockerfile: Dockerfile
        image: cryptobets-service:latest
        ports:
            - 7000:7000
        networks:
            - crytpobets-network
        depends_on:
            - kafka
            - zookeeper
            - config-service
networks:
    crytpobets-network:
        driver: bridge